### ISSUE TITLE
Word(s) missing in sentence

### ISSUE THREAD

**Issue by securibee** [hxnyk/BLM-resources#1]
There seems to be a word missing in the first sentence, "in regards to the ."

https://github.com/hxnyk/BLM-resources/blob/da5f8b20a352afc8c5e17d79fc800d4c8c12c5ff/src/twitterbot.html#L40

🐝

**Comment by d0nutptr** [comment]
Thanks! We'll get that fixed soon :)

**Comment by hxnyk** [comment]
Fixed -- thank you! 🍯
